# Generated by Django 4.2.7 on 2025-11-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('GESTURE', 'Gesture Detection'), ('SESSION', 'Session Event'), ('FACE', 'Face Detection'), ('ERROR', 'Error'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('event_name', models.CharField(help_text='e.g., STUDENT_CLAPPED, STUDENT_LEFT_SCREEN', max_length=100)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional event metadata', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='monitor_eve_timesta_46761c_idx'), models.Index(fields=['event_type', '-timestamp'], name='monitor_eve_event_t_ae14a9_idx'), models.Index(fields=['username', '-timestamp'], name='monitor_eve_usernam_a324b8_idx')],
            },
        ),
    ]
